GET http://localhost:3001/api/tasks
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2MjZiMzFjMmYxOTM0MzBhNmVlNzFiN2UiLCJmaXJzdE5hbWUiOiJEb25hbGQiLCJsYXN0TmFtZSI6IlN1cnlhIiwiaGFuZGxlIjoibmV3cGFsdHpfYmVuZXZvbGVudCIsImVtYWlsIjoiU3VyeWFAU3VyeWEuY29tIiwicGljIjoiaHR0cHM6Ly9yYW5kb211c2VyLm1lL2FwaS9wb3J0cmFpdHMvbWVuLzIuanBnIiwiaWQiOjUsImlhdCI6MTY1MTIwNTU1OH0.egYs7ZEEk9gSmW2i5QXaMA8o9Mji93nYjJhc6K3x8gE

###
GET http://localhost:3001/api/tasks/wall/vp
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2MjZiMzEwOWYxOTM0MzBhNmVlNzFiN2QiLCJmaXJzdE5hbWUiOiJEb25hbGQiLCJsYXN0TmFtZSI6IkNocmlzdGlhbiIsImhhbmRsZSI6Im5ld3BhbHR6X2JlbmV2b2xlbnQiLCJlbWFpbCI6InByZXNpZGVudEBuZXdwYWx0ei5lZHUiLCJwaWMiOiJodHRwczovL3JhbmRvbXVzZXIubWUvYXBpL3BvcnRyYWl0cy9tZW4vMi5qcGciLCJpZCI6NCwiaWF0IjoxNjUxMTkyMDkyfQ._pm1Vs2SB1CTYbeSIgNTxrH5564zzInIf08Ol4W1NFo

###
GET http://localhost:3001/api/tasks/626b4c565443efa215a371e8
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2MjZiMzEwOWYxOTM0MzBhNmVlNzFiN2QiLCJmaXJzdE5hbWUiOiJEb25hbGQiLCJsYXN0TmFtZSI6IkNocmlzdGlhbiIsImhhbmRsZSI6Im5ld3BhbHR6X2JlbmV2b2xlbnQiLCJlbWFpbCI6InByZXNpZGVudEBuZXdwYWx0ei5lZHUiLCJwaWMiOiJodHRwczovL3JhbmRvbXVzZXIubWUvYXBpL3BvcnRyYWl0cy9tZW4vMi5qcGciLCJpZCI6NCwiaWF0IjoxNjUxMTkyMDkyfQ._pm1Vs2SB1CTYbeSIgNTxrH5564zzInIf08Ol4W1NFo

###
DELETE  http://localhost:3001/api/tasks/626b5368171fe00110917a07
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2MjZiMzEwOWYxOTM0MzBhNmVlNzFiN2QiLCJmaXJzdE5hbWUiOiJEb25hbGQiLCJsYXN0TmFtZSI6IkNocmlzdGlhbiIsImhhbmRsZSI6Im5ld3BhbHR6X2JlbmV2b2xlbnQiLCJlbWFpbCI6InByZXNpZGVudEBuZXdwYWx0ei5lZHUiLCJwaWMiOiJodHRwczovL3JhbmRvbXVzZXIubWUvYXBpL3BvcnRyYWl0cy9tZW4vMi5qcGciLCJpZCI6NCwiaWF0IjoxNjUxMTkyMDkyfQ._pm1Vs2SB1CTYbeSIgNTxrH5564zzInIf08Ol4W1NFo

###
POST http://localhost:3001/api/tasks
Content-Type: application/json
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2MjZiMzEwOWYxOTM0MzBhNmVlNzFiN2QiLCJmaXJzdE5hbWUiOiJEb25hbGQiLCJsYXN0TmFtZSI6IkNocmlzdGlhbiIsImhhbmRsZSI6Im5ld3BhbHR6X2JlbmV2b2xlbnQiLCJlbWFpbCI6InByZXNpZGVudEBuZXdwYWx0ei5lZHUiLCJwaWMiOiJodHRwczovL3JhbmRvbXVzZXIubWUvYXBpL3BvcnRyYWl0cy9tZW4vMi5qcGciLCJpZCI6NCwiaWF0IjoxNjUxMTkyMDkyfQ._pm1Vs2SB1CTYbeSIgNTxrH5564zzInIf08Ol4W1NFo


    {
        "id": 1,
        "task": "Create a task",
        "isCompleted": false,
        "assignedTo": "626b31c2f193430a6ee71b7e",
        "assignedBy": "626b31c2f193430a6ee71b7e"
     }


###
PATCH http://localhost:3001/api/tasks/6257fccb2efcbef8bf5d99ee
Content-Type: application/json
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2MjZiMzEwOWYxOTM0MzBhNmVlNzFiN2QiLCJmaXJzdE5hbWUiOiJEb25hbGQiLCJsYXN0TmFtZSI6IkNocmlzdGlhbiIsImhhbmRsZSI6Im5ld3BhbHR6X2JlbmV2b2xlbnQiLCJlbWFpbCI6InByZXNpZGVudEBuZXdwYWx0ei5lZHUiLCJwaWMiOiJodHRwczovL3JhbmRvbXVzZXIubWUvYXBpL3BvcnRyYWl0cy9tZW4vMi5qcGciLCJpZCI6NCwiaWF0IjoxNjUxMTkyMDkyfQ._pm1Vs2SB1CTYbeSIgNTxrH5564zzInIf08Ol4W1NFo

{
    "owner": "newpaltz_benevolent"
}

###
POST http://localhost:3001/api/tasks/seed
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2MjZiMzEwOWYxOTM0MzBhNmVlNzFiN2QiLCJmaXJzdE5hbWUiOiJEb25hbGQiLCJsYXN0TmFtZSI6IkNocmlzdGlhbiIsImhhbmRsZSI6Im5ld3BhbHR6X2JlbmV2b2xlbnQiLCJlbWFpbCI6InByZXNpZGVudEBuZXdwYWx0ei5lZHUiLCJwaWMiOiJodHRwczovL3JhbmRvbXVzZXIubWUvYXBpL3BvcnRyYWl0cy9tZW4vMi5qcGciLCJpZCI6NCwiaWF0IjoxNjUxMTkyMDkyfQ._pm1Vs2SB1CTYbeSIgNTxrH5564zzInIf08Ol4W1NFo
